services:
  db:
    image: postgis/postgis:latest
    container_name: postgres-postgis
    environment:
      POSTGRES_DB: power_outage_db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: secure_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: postgres_power_outage_data
